version: '3.8'

services:
  rcg-api:
    image: ricardops34/rcg-backend:latest
    build: ./backend
    networks:
      - network_db
      - network_public
    environment:
      - DB_HOST=postgres  # Nome do host do banco na rede externa network_db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=admin
      - DB_DATABASE=rcgcrm
      - JWT_SECRET=${JWT_SECRET}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_SEED=${DB_SEED:-false}
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.rcg-api.rule=Host(`crmapi.bjsoft.com.br`)"
        - "traefik.http.routers.rcg-api.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.rcg-api.middlewares=sslheader@swarm"
        - "traefik.http.routers.rcg-api.entrypoints=websecure"
        - "traefik.http.services.rcg-api.loadbalancer.server.port=3000"
        - "traefik.docker.network=network_public"

  rcg-web:
    image: ricardops34/rcg-frontend:latest
    build: ./frontend
    networks:
      - network_public
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.rcg-web.rule=Host(`crm.bjsoft.com.br`) || HostRegexp(`{subdomain:[a-z0-9]+}.crm.bjsoft.com.br`)"
        - "traefik.http.routers.rcg-web.entrypoints=websecure"
        - "traefik.http.routers.rcg-web.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.rcg-web.middlewares=sslheader@swarm"
        - "traefik.http.services.rcg-web.loadbalancer.server.port=80"
        - "traefik.docker.network=network_public"

networks:
  network_db:
    external: true
  network_public:
    external: true

