[builder]
app_url = "https://app.madbuilder.com.br"
manager_url = "https://code.madbuilder.com.br"
services_url = "https://services.madbuilder.com.br"
version = "4.2"

[general]
timezone = America/Campo_Grande
language = pt
application = rcg
title = "RCG"
require_terms = 0
theme = theme-builder
dialog_box_type = "sweetalert"
multiunit = 1
change_unit = 1
request_unit_after_login = 1
locale = pt-BR
token = e2c3ce0fcbbd6137af3fac572f5b198efb5bf401dda15292271d9876837bdbc4986868
seed = c9f461bc5e1fee54d4ac9ee27ea81221a0d48a3f
rest_key = c001b9425c89d06d3bb829b004fd4e04327cf928dafe3d29ca5684c0b3bb
debug = 0
multi_lang = "0"
left_menu = "1"
top_menu = "0"
verify_messages_menu = "30000"
verify_notifications_menu = "30000"
default_units = ""
use_tabs = 0
store_tabs = 0
use_mdi_windows = 0
store_mdi_windows = 0
notification_login = 1
left_menu_modules = "0"
top_menu_modules = "0"
application_version = "1.5"
main_database = "erp_online"

;request_log_service = SystemRequestLogService
;request_log = 1
;request_log_types = cli,web,rest


multi_database = "0"

public_view = "0"
public_entry = "PublicView"
theme_mobile = theme-builder

[user_public_pages]


[permission]

user_register    = "0"  ; users may auto register
reset_password   = "0"  ; users may reset password
default_groups   = "2"  ; default groups for auto registered users
default_units    = "1"  ; default units for auto registered users
default_screen   = "10" ; default screen for auto registered users
single_user_session = 1

auth_service = CustomAuthenticationService

; Public classes, anyone (logged or not) has access
public_classes[] = PublicForm
public_classes[] = PublicView
public_classes[] = DatabaseInstall
public_classes[] = ExtensionsInstall
public_classes[] = PathInstall
public_classes[] = SummaryDatabaseInstall
public_classes[] = SystemModulesCheckView
public_classes[] = AdiantiMultiSearchService
public_classes[] = AdiantiUploaderService
public_classes[] = AdiantiAutocompleteService

public_classes[] = pedidoChatWoot
public_classes[] = FormLoginCliente
public_classes[] = LoginClienteForm
public_classes[] = PainelClienteForm
public_classes[] = ClientePublicaFormView
public_classes[] = AtualizaCliente
public_classes[] = MeuClienteFormView
public_classes[] = ProdutoSite